version: '3.8'
services:
  thelounge:
    image: thelounge/thelounge:latest
    restart: unless-stopped
    volumes:
      - thelounge:/var/opt/thelounge
    labels:
      - traefik.enable=true
      - traefik.http.routers.thelounge.rule=Host(`irc.shyim.de`)
      - traefik.http.routers.thelounge.entrypoints=websecure
      - traefik.http.routers.thelounge.tls=true
      - traefik.http.routers.thelounge.tls.certresolver=letsencrypt
      - traefik.http.routers.thelounge.middlewares=compress
    networks:
      - traefik
volumes:
  thelounge:
    name: shea_thelounge
    external: true
