version: '3.8'
services:
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: wakapi
      MYSQL_PASSWORD: wakapi
      MYSQL_DATABASE: wakapi
    volumes:
      - wakapi-mysql:/var/lib/mysql
    networks:
      - wakapi

  wakapi:
    image: ghcr.io/muety/wakapi:latest
    restart: unless-stopped
    environment:
      ENVIRONMENT: prod
      WAKAPI_PASSWORD_SALT: ""
      WAKAPI_DB_HOST: "mysql"
      WAKAPI_DB_PORT: "3306"
      WAKAPI_DB_USER: "wakapi"
      WAKAPI_DB_PASSWORD: "wakapi"
      WAKAPI_DB_NAME: "wakapi"
      WAKAPI_DB_TYPE: "mysql"
      WAKAPI_MAIL_ENABLED: "true"
      WAKAPI_MAIL_PROVIDER: "smtp"
      WAKAPI_MAIL_SENDER: "Wakapi <contact@fos.gg>"
      WAKAPI_MAIL_SMTP_HOST: "smtp.mail.me.com"
      WAKAPI_MAIL_SMTP_PORT: "587"
      WAKAPI_MAIL_SMTP_USER: "s.sayakci@icloud.com"
      MAIL_PASSWORD: ${WAKAPI_MAIL_PASSWORD}
    networks:
      - wakapi
      - traefik
    labels:
      - traefik.http.middlewares.compress.compress=true
      - traefik.enable=true
      - traefik.http.routers.wakapi.rule=Host(`time.fos.gg`)
      - traefik.http.routers.wakapi.entrypoints=websecure
      - traefik.http.routers.wakapi.tls=true
      - traefik.http.routers.wakapi.tls.certresolver=letsencrypt
      - traefik.http.routers.wakapi.middlewares=compress

volumes:
  wakapi-mysql:
    name: shea_wakapi-mysql

networks:
  wakapi:
